app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:3306/jdbc
      password: 'password'
      pool-size: 30
      username: root

server:
  error:
    include-binding-errors: always
    include-message: always

